/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HotelesRouteImport } from './routes/hoteles'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArmaTuViajeRouteImport } from './routes/arma-tu-viaje'
import { Route as AluxRouteImport } from './routes/alux'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrienteMayaIndexRouteImport } from './routes/oriente-maya/index'
import { Route as OrienteMayaDestinoRouteImport } from './routes/oriente-maya/$destino'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedCmsIndexRouteImport } from './routes/_authenticated/cms/index'
import { Route as AuthenticatedPortalPresenciaRouteImport } from './routes/_authenticated/portal/presencia'
import { Route as AuthenticatedPortalGaleriaRouteImport } from './routes/_authenticated/portal/galeria'
import { Route as AuthenticatedPortalFichaRouteImport } from './routes/_authenticated/portal/ficha'
import { Route as AuthenticatedPortalCatalogoRouteImport } from './routes/_authenticated/portal/catalogo'
import { Route as AuthenticatedCmsZonasRouteImport } from './routes/_authenticated/cms/zonas'
import { Route as AuthenticatedCmsProductosRouteImport } from './routes/_authenticated/cms/productos'
import { Route as AuthenticatedCmsMediaRouteImport } from './routes/_authenticated/cms/media'
import { Route as AuthenticatedCmsEmpresasRouteImport } from './routes/_authenticated/cms/empresas'
import { Route as AuthenticatedCmsDestinosRouteImport } from './routes/_authenticated/cms/destinos'
import { Route as AuthenticatedPortalInvitacionesIndexRouteImport } from './routes/_authenticated/portal/invitaciones.index'
import { Route as AuthenticatedCmsReviewsIndexRouteImport } from './routes/_authenticated/cms/reviews.index'
import { Route as AuthenticatedCmsRegionesIndexRouteImport } from './routes/_authenticated/cms/regiones.index'
import { Route as AuthenticatedCmsCategoriasIndexRouteImport } from './routes/_authenticated/cms/categorias.index'
import { Route as AuthenticatedPortalInvitacionesTokenRouteImport } from './routes/_authenticated/portal/invitaciones.$token'
import { Route as AuthenticatedCmsRegionesNuevaRouteImport } from './routes/_authenticated/cms/regiones.nueva'
import { Route as AuthenticatedCmsRegionesEditarRouteImport } from './routes/_authenticated/cms/regiones..editar'
import { Route as AuthenticatedCmsCategoriasNuevaRouteImport } from './routes/_authenticated/cms/categorias.nueva'
import { Route as AuthenticatedCmsCategoriasEditarRouteImport } from './routes/_authenticated/cms/categorias..editar'
import { Route as AuthenticatedCmsReviewsIdModerarRouteImport } from './routes/_authenticated/cms/reviews.$id.moderar'

const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesRoute = HotelesRouteImport.update({
  id: '/hoteles',
  path: '/hoteles',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmaTuViajeRoute = ArmaTuViajeRouteImport.update({
  id: '/arma-tu-viaje',
  path: '/arma-tu-viaje',
  getParentRoute: () => rootRouteImport,
} as any)
const AluxRoute = AluxRouteImport.update({
  id: '/alux',
  path: '/alux',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrienteMayaIndexRoute = OrienteMayaIndexRouteImport.update({
  id: '/oriente-maya/',
  path: '/oriente-maya/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrienteMayaDestinoRoute = OrienteMayaDestinoRouteImport.update({
  id: '/oriente-maya/$destino',
  path: '/oriente-maya/$destino',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedCmsIndexRoute = AuthenticatedCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedPortalPresenciaRoute =
  AuthenticatedPortalPresenciaRouteImport.update({
    id: '/presencia',
    path: '/presencia',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalGaleriaRoute =
  AuthenticatedPortalGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalFichaRoute =
  AuthenticatedPortalFichaRouteImport.update({
    id: '/ficha',
    path: '/ficha',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCatalogoRoute =
  AuthenticatedPortalCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedCmsZonasRoute = AuthenticatedCmsZonasRouteImport.update({
  id: '/zonas',
  path: '/zonas',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsProductosRoute =
  AuthenticatedCmsProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsMediaRoute = AuthenticatedCmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsEmpresasRoute =
  AuthenticatedCmsEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsDestinosRoute =
  AuthenticatedCmsDestinosRouteImport.update({
    id: '/destinos',
    path: '/destinos',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedPortalInvitacionesIndexRoute =
  AuthenticatedPortalInvitacionesIndexRouteImport.update({
    id: '/invitaciones/',
    path: '/invitaciones/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedCmsReviewsIndexRoute =
  AuthenticatedCmsReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsRegionesIndexRoute =
  AuthenticatedCmsRegionesIndexRouteImport.update({
    id: '/regiones/',
    path: '/regiones/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsCategoriasIndexRoute =
  AuthenticatedCmsCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedPortalInvitacionesTokenRoute =
  AuthenticatedPortalInvitacionesTokenRouteImport.update({
    id: '/invitaciones/$token',
    path: '/invitaciones/$token',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedCmsRegionesNuevaRoute =
  AuthenticatedCmsRegionesNuevaRouteImport.update({
    id: '/regiones/nueva',
    path: '/regiones/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsRegionesEditarRoute =
  AuthenticatedCmsRegionesEditarRouteImport.update({
    id: '/regiones/editar',
    path: '/regiones/editar',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsCategoriasNuevaRoute =
  AuthenticatedCmsCategoriasNuevaRouteImport.update({
    id: '/categorias/nueva',
    path: '/categorias/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsCategoriasEditarRoute =
  AuthenticatedCmsCategoriasEditarRouteImport.update({
    id: '/categorias/editar',
    path: '/categorias/editar',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsReviewsIdModerarRoute =
  AuthenticatedCmsReviewsIdModerarRouteImport.update({
    id: '/reviews/$id/moderar',
    path: '/reviews/$id/moderar',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alux': typeof AluxRoute
  '/arma-tu-viaje': typeof ArmaTuViajeRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/eventos': typeof EventosRoute
  '/experiencias': typeof ExperienciasRoute
  '/hoteles': typeof HotelesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurantes': typeof RestaurantesRoute
  '/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/cms': typeof AuthenticatedCmsRouteWithChildren
  '/oriente-maya/$destino': typeof OrienteMayaDestinoRoute
  '/oriente-maya/': typeof OrienteMayaIndexRoute
  '/cms/destinos': typeof AuthenticatedCmsDestinosRoute
  '/cms/empresas': typeof AuthenticatedCmsEmpresasRoute
  '/cms/media': typeof AuthenticatedCmsMediaRoute
  '/cms/productos': typeof AuthenticatedCmsProductosRoute
  '/cms/zonas': typeof AuthenticatedCmsZonasRoute
  '/portal/catalogo': typeof AuthenticatedPortalCatalogoRoute
  '/portal/ficha': typeof AuthenticatedPortalFichaRoute
  '/portal/galeria': typeof AuthenticatedPortalGaleriaRoute
  '/portal/presencia': typeof AuthenticatedPortalPresenciaRoute
  '/cms/': typeof AuthenticatedCmsIndexRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/cms/categorias/editar': typeof AuthenticatedCmsCategoriasEditarRoute
  '/cms/categorias/nueva': typeof AuthenticatedCmsCategoriasNuevaRoute
  '/cms/regiones/editar': typeof AuthenticatedCmsRegionesEditarRoute
  '/cms/regiones/nueva': typeof AuthenticatedCmsRegionesNuevaRoute
  '/portal/invitaciones/$token': typeof AuthenticatedPortalInvitacionesTokenRoute
  '/cms/categorias/': typeof AuthenticatedCmsCategoriasIndexRoute
  '/cms/regiones/': typeof AuthenticatedCmsRegionesIndexRoute
  '/cms/reviews/': typeof AuthenticatedCmsReviewsIndexRoute
  '/portal/invitaciones/': typeof AuthenticatedPortalInvitacionesIndexRoute
  '/cms/reviews/$id/moderar': typeof AuthenticatedCmsReviewsIdModerarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alux': typeof AluxRoute
  '/arma-tu-viaje': typeof ArmaTuViajeRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/eventos': typeof EventosRoute
  '/experiencias': typeof ExperienciasRoute
  '/hoteles': typeof HotelesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurantes': typeof RestaurantesRoute
  '/oriente-maya/$destino': typeof OrienteMayaDestinoRoute
  '/oriente-maya': typeof OrienteMayaIndexRoute
  '/cms/destinos': typeof AuthenticatedCmsDestinosRoute
  '/cms/empresas': typeof AuthenticatedCmsEmpresasRoute
  '/cms/media': typeof AuthenticatedCmsMediaRoute
  '/cms/productos': typeof AuthenticatedCmsProductosRoute
  '/cms/zonas': typeof AuthenticatedCmsZonasRoute
  '/portal/catalogo': typeof AuthenticatedPortalCatalogoRoute
  '/portal/ficha': typeof AuthenticatedPortalFichaRoute
  '/portal/galeria': typeof AuthenticatedPortalGaleriaRoute
  '/portal/presencia': typeof AuthenticatedPortalPresenciaRoute
  '/cms': typeof AuthenticatedCmsIndexRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/cms/categorias/editar': typeof AuthenticatedCmsCategoriasEditarRoute
  '/cms/categorias/nueva': typeof AuthenticatedCmsCategoriasNuevaRoute
  '/cms/regiones/editar': typeof AuthenticatedCmsRegionesEditarRoute
  '/cms/regiones/nueva': typeof AuthenticatedCmsRegionesNuevaRoute
  '/portal/invitaciones/$token': typeof AuthenticatedPortalInvitacionesTokenRoute
  '/cms/categorias': typeof AuthenticatedCmsCategoriasIndexRoute
  '/cms/regiones': typeof AuthenticatedCmsRegionesIndexRoute
  '/cms/reviews': typeof AuthenticatedCmsReviewsIndexRoute
  '/portal/invitaciones': typeof AuthenticatedPortalInvitacionesIndexRoute
  '/cms/reviews/$id/moderar': typeof AuthenticatedCmsReviewsIdModerarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/alux': typeof AluxRoute
  '/arma-tu-viaje': typeof ArmaTuViajeRoute
  '/auth': typeof AuthRoute
  '/empresas': typeof EmpresasRoute
  '/eventos': typeof EventosRoute
  '/experiencias': typeof ExperienciasRoute
  '/hoteles': typeof HotelesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurantes': typeof RestaurantesRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRouteRouteWithChildren
  '/_authenticated/cms': typeof AuthenticatedCmsRouteWithChildren
  '/oriente-maya/$destino': typeof OrienteMayaDestinoRoute
  '/oriente-maya/': typeof OrienteMayaIndexRoute
  '/_authenticated/cms/destinos': typeof AuthenticatedCmsDestinosRoute
  '/_authenticated/cms/empresas': typeof AuthenticatedCmsEmpresasRoute
  '/_authenticated/cms/media': typeof AuthenticatedCmsMediaRoute
  '/_authenticated/cms/productos': typeof AuthenticatedCmsProductosRoute
  '/_authenticated/cms/zonas': typeof AuthenticatedCmsZonasRoute
  '/_authenticated/portal/catalogo': typeof AuthenticatedPortalCatalogoRoute
  '/_authenticated/portal/ficha': typeof AuthenticatedPortalFichaRoute
  '/_authenticated/portal/galeria': typeof AuthenticatedPortalGaleriaRoute
  '/_authenticated/portal/presencia': typeof AuthenticatedPortalPresenciaRoute
  '/_authenticated/cms/': typeof AuthenticatedCmsIndexRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/cms/categorias/editar': typeof AuthenticatedCmsCategoriasEditarRoute
  '/_authenticated/cms/categorias/nueva': typeof AuthenticatedCmsCategoriasNuevaRoute
  '/_authenticated/cms/regiones/editar': typeof AuthenticatedCmsRegionesEditarRoute
  '/_authenticated/cms/regiones/nueva': typeof AuthenticatedCmsRegionesNuevaRoute
  '/_authenticated/portal/invitaciones/$token': typeof AuthenticatedPortalInvitacionesTokenRoute
  '/_authenticated/cms/categorias/': typeof AuthenticatedCmsCategoriasIndexRoute
  '/_authenticated/cms/regiones/': typeof AuthenticatedCmsRegionesIndexRoute
  '/_authenticated/cms/reviews/': typeof AuthenticatedCmsReviewsIndexRoute
  '/_authenticated/portal/invitaciones/': typeof AuthenticatedPortalInvitacionesIndexRoute
  '/_authenticated/cms/reviews/$id/moderar': typeof AuthenticatedCmsReviewsIdModerarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alux'
    | '/arma-tu-viaje'
    | '/auth'
    | '/empresas'
    | '/eventos'
    | '/experiencias'
    | '/hoteles'
    | '/reset-password'
    | '/restaurantes'
    | '/portal'
    | '/cms'
    | '/oriente-maya/$destino'
    | '/oriente-maya/'
    | '/cms/destinos'
    | '/cms/empresas'
    | '/cms/media'
    | '/cms/productos'
    | '/cms/zonas'
    | '/portal/catalogo'
    | '/portal/ficha'
    | '/portal/galeria'
    | '/portal/presencia'
    | '/cms/'
    | '/portal/'
    | '/cms/categorias/editar'
    | '/cms/categorias/nueva'
    | '/cms/regiones/editar'
    | '/cms/regiones/nueva'
    | '/portal/invitaciones/$token'
    | '/cms/categorias/'
    | '/cms/regiones/'
    | '/cms/reviews/'
    | '/portal/invitaciones/'
    | '/cms/reviews/$id/moderar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alux'
    | '/arma-tu-viaje'
    | '/auth'
    | '/empresas'
    | '/eventos'
    | '/experiencias'
    | '/hoteles'
    | '/reset-password'
    | '/restaurantes'
    | '/oriente-maya/$destino'
    | '/oriente-maya'
    | '/cms/destinos'
    | '/cms/empresas'
    | '/cms/media'
    | '/cms/productos'
    | '/cms/zonas'
    | '/portal/catalogo'
    | '/portal/ficha'
    | '/portal/galeria'
    | '/portal/presencia'
    | '/cms'
    | '/portal'
    | '/cms/categorias/editar'
    | '/cms/categorias/nueva'
    | '/cms/regiones/editar'
    | '/cms/regiones/nueva'
    | '/portal/invitaciones/$token'
    | '/cms/categorias'
    | '/cms/regiones'
    | '/cms/reviews'
    | '/portal/invitaciones'
    | '/cms/reviews/$id/moderar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alux'
    | '/arma-tu-viaje'
    | '/auth'
    | '/empresas'
    | '/eventos'
    | '/experiencias'
    | '/hoteles'
    | '/reset-password'
    | '/restaurantes'
    | '/_authenticated/portal'
    | '/_authenticated/cms'
    | '/oriente-maya/$destino'
    | '/oriente-maya/'
    | '/_authenticated/cms/destinos'
    | '/_authenticated/cms/empresas'
    | '/_authenticated/cms/media'
    | '/_authenticated/cms/productos'
    | '/_authenticated/cms/zonas'
    | '/_authenticated/portal/catalogo'
    | '/_authenticated/portal/ficha'
    | '/_authenticated/portal/galeria'
    | '/_authenticated/portal/presencia'
    | '/_authenticated/cms/'
    | '/_authenticated/portal/'
    | '/_authenticated/cms/categorias/editar'
    | '/_authenticated/cms/categorias/nueva'
    | '/_authenticated/cms/regiones/editar'
    | '/_authenticated/cms/regiones/nueva'
    | '/_authenticated/portal/invitaciones/$token'
    | '/_authenticated/cms/categorias/'
    | '/_authenticated/cms/regiones/'
    | '/_authenticated/cms/reviews/'
    | '/_authenticated/portal/invitaciones/'
    | '/_authenticated/cms/reviews/$id/moderar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AluxRoute: typeof AluxRoute
  ArmaTuViajeRoute: typeof ArmaTuViajeRoute
  AuthRoute: typeof AuthRoute
  EmpresasRoute: typeof EmpresasRoute
  EventosRoute: typeof EventosRoute
  ExperienciasRoute: typeof ExperienciasRoute
  HotelesRoute: typeof HotelesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantesRoute: typeof RestaurantesRoute
  OrienteMayaDestinoRoute: typeof OrienteMayaDestinoRoute
  OrienteMayaIndexRoute: typeof OrienteMayaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurantes': {
      id: '/restaurantes'
      path: '/restaurantes'
      fullPath: '/restaurantes'
      preLoaderRoute: typeof RestaurantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoteles': {
      id: '/hoteles'
      path: '/hoteles'
      fullPath: '/hoteles'
      preLoaderRoute: typeof HotelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arma-tu-viaje': {
      id: '/arma-tu-viaje'
      path: '/arma-tu-viaje'
      fullPath: '/arma-tu-viaje'
      preLoaderRoute: typeof ArmaTuViajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alux': {
      id: '/alux'
      path: '/alux'
      fullPath: '/alux'
      preLoaderRoute: typeof AluxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oriente-maya/': {
      id: '/oriente-maya/'
      path: '/oriente-maya'
      fullPath: '/oriente-maya/'
      preLoaderRoute: typeof OrienteMayaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oriente-maya/$destino': {
      id: '/oriente-maya/$destino'
      path: '/oriente-maya/$destino'
      fullPath: '/oriente-maya/$destino'
      preLoaderRoute: typeof OrienteMayaDestinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/cms/': {
      id: '/_authenticated/cms/'
      path: '/'
      fullPath: '/cms/'
      preLoaderRoute: typeof AuthenticatedCmsIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/portal/presencia': {
      id: '/_authenticated/portal/presencia'
      path: '/presencia'
      fullPath: '/portal/presencia'
      preLoaderRoute: typeof AuthenticatedPortalPresenciaRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/galeria': {
      id: '/_authenticated/portal/galeria'
      path: '/galeria'
      fullPath: '/portal/galeria'
      preLoaderRoute: typeof AuthenticatedPortalGaleriaRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/ficha': {
      id: '/_authenticated/portal/ficha'
      path: '/ficha'
      fullPath: '/portal/ficha'
      preLoaderRoute: typeof AuthenticatedPortalFichaRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/portal/catalogo': {
      id: '/_authenticated/portal/catalogo'
      path: '/catalogo'
      fullPath: '/portal/catalogo'
      preLoaderRoute: typeof AuthenticatedPortalCatalogoRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/cms/zonas': {
      id: '/_authenticated/cms/zonas'
      path: '/zonas'
      fullPath: '/cms/zonas'
      preLoaderRoute: typeof AuthenticatedCmsZonasRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/productos': {
      id: '/_authenticated/cms/productos'
      path: '/productos'
      fullPath: '/cms/productos'
      preLoaderRoute: typeof AuthenticatedCmsProductosRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/media': {
      id: '/_authenticated/cms/media'
      path: '/media'
      fullPath: '/cms/media'
      preLoaderRoute: typeof AuthenticatedCmsMediaRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/empresas': {
      id: '/_authenticated/cms/empresas'
      path: '/empresas'
      fullPath: '/cms/empresas'
      preLoaderRoute: typeof AuthenticatedCmsEmpresasRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/destinos': {
      id: '/_authenticated/cms/destinos'
      path: '/destinos'
      fullPath: '/cms/destinos'
      preLoaderRoute: typeof AuthenticatedCmsDestinosRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/portal/invitaciones/': {
      id: '/_authenticated/portal/invitaciones/'
      path: '/invitaciones'
      fullPath: '/portal/invitaciones/'
      preLoaderRoute: typeof AuthenticatedPortalInvitacionesIndexRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/cms/reviews/': {
      id: '/_authenticated/cms/reviews/'
      path: '/reviews'
      fullPath: '/cms/reviews/'
      preLoaderRoute: typeof AuthenticatedCmsReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/regiones/': {
      id: '/_authenticated/cms/regiones/'
      path: '/regiones'
      fullPath: '/cms/regiones/'
      preLoaderRoute: typeof AuthenticatedCmsRegionesIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/categorias/': {
      id: '/_authenticated/cms/categorias/'
      path: '/categorias'
      fullPath: '/cms/categorias/'
      preLoaderRoute: typeof AuthenticatedCmsCategoriasIndexRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/portal/invitaciones/$token': {
      id: '/_authenticated/portal/invitaciones/$token'
      path: '/invitaciones/$token'
      fullPath: '/portal/invitaciones/$token'
      preLoaderRoute: typeof AuthenticatedPortalInvitacionesTokenRouteImport
      parentRoute: typeof AuthenticatedPortalRouteRoute
    }
    '/_authenticated/cms/regiones/nueva': {
      id: '/_authenticated/cms/regiones/nueva'
      path: '/regiones/nueva'
      fullPath: '/cms/regiones/nueva'
      preLoaderRoute: typeof AuthenticatedCmsRegionesNuevaRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/regiones/editar': {
      id: '/_authenticated/cms/regiones/editar'
      path: '/regiones/editar'
      fullPath: '/cms/regiones/editar'
      preLoaderRoute: typeof AuthenticatedCmsRegionesEditarRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/categorias/nueva': {
      id: '/_authenticated/cms/categorias/nueva'
      path: '/categorias/nueva'
      fullPath: '/cms/categorias/nueva'
      preLoaderRoute: typeof AuthenticatedCmsCategoriasNuevaRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/categorias/editar': {
      id: '/_authenticated/cms/categorias/editar'
      path: '/categorias/editar'
      fullPath: '/cms/categorias/editar'
      preLoaderRoute: typeof AuthenticatedCmsCategoriasEditarRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
    '/_authenticated/cms/reviews/$id/moderar': {
      id: '/_authenticated/cms/reviews/$id/moderar'
      path: '/reviews/$id/moderar'
      fullPath: '/cms/reviews/$id/moderar'
      preLoaderRoute: typeof AuthenticatedCmsReviewsIdModerarRouteImport
      parentRoute: typeof AuthenticatedCmsRoute
    }
  }
}

interface AuthenticatedPortalRouteRouteChildren {
  AuthenticatedPortalCatalogoRoute: typeof AuthenticatedPortalCatalogoRoute
  AuthenticatedPortalFichaRoute: typeof AuthenticatedPortalFichaRoute
  AuthenticatedPortalGaleriaRoute: typeof AuthenticatedPortalGaleriaRoute
  AuthenticatedPortalPresenciaRoute: typeof AuthenticatedPortalPresenciaRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedPortalInvitacionesTokenRoute: typeof AuthenticatedPortalInvitacionesTokenRoute
  AuthenticatedPortalInvitacionesIndexRoute: typeof AuthenticatedPortalInvitacionesIndexRoute
}

const AuthenticatedPortalRouteRouteChildren: AuthenticatedPortalRouteRouteChildren =
  {
    AuthenticatedPortalCatalogoRoute: AuthenticatedPortalCatalogoRoute,
    AuthenticatedPortalFichaRoute: AuthenticatedPortalFichaRoute,
    AuthenticatedPortalGaleriaRoute: AuthenticatedPortalGaleriaRoute,
    AuthenticatedPortalPresenciaRoute: AuthenticatedPortalPresenciaRoute,
    AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
    AuthenticatedPortalInvitacionesTokenRoute:
      AuthenticatedPortalInvitacionesTokenRoute,
    AuthenticatedPortalInvitacionesIndexRoute:
      AuthenticatedPortalInvitacionesIndexRoute,
  }

const AuthenticatedPortalRouteRouteWithChildren =
  AuthenticatedPortalRouteRoute._addFileChildren(
    AuthenticatedPortalRouteRouteChildren,
  )

interface AuthenticatedCmsRouteChildren {
  AuthenticatedCmsDestinosRoute: typeof AuthenticatedCmsDestinosRoute
  AuthenticatedCmsEmpresasRoute: typeof AuthenticatedCmsEmpresasRoute
  AuthenticatedCmsMediaRoute: typeof AuthenticatedCmsMediaRoute
  AuthenticatedCmsProductosRoute: typeof AuthenticatedCmsProductosRoute
  AuthenticatedCmsZonasRoute: typeof AuthenticatedCmsZonasRoute
  AuthenticatedCmsIndexRoute: typeof AuthenticatedCmsIndexRoute
  AuthenticatedCmsCategoriasEditarRoute: typeof AuthenticatedCmsCategoriasEditarRoute
  AuthenticatedCmsCategoriasNuevaRoute: typeof AuthenticatedCmsCategoriasNuevaRoute
  AuthenticatedCmsRegionesEditarRoute: typeof AuthenticatedCmsRegionesEditarRoute
  AuthenticatedCmsRegionesNuevaRoute: typeof AuthenticatedCmsRegionesNuevaRoute
  AuthenticatedCmsCategoriasIndexRoute: typeof AuthenticatedCmsCategoriasIndexRoute
  AuthenticatedCmsRegionesIndexRoute: typeof AuthenticatedCmsRegionesIndexRoute
  AuthenticatedCmsReviewsIndexRoute: typeof AuthenticatedCmsReviewsIndexRoute
  AuthenticatedCmsReviewsIdModerarRoute: typeof AuthenticatedCmsReviewsIdModerarRoute
}

const AuthenticatedCmsRouteChildren: AuthenticatedCmsRouteChildren = {
  AuthenticatedCmsDestinosRoute: AuthenticatedCmsDestinosRoute,
  AuthenticatedCmsEmpresasRoute: AuthenticatedCmsEmpresasRoute,
  AuthenticatedCmsMediaRoute: AuthenticatedCmsMediaRoute,
  AuthenticatedCmsProductosRoute: AuthenticatedCmsProductosRoute,
  AuthenticatedCmsZonasRoute: AuthenticatedCmsZonasRoute,
  AuthenticatedCmsIndexRoute: AuthenticatedCmsIndexRoute,
  AuthenticatedCmsCategoriasEditarRoute: AuthenticatedCmsCategoriasEditarRoute,
  AuthenticatedCmsCategoriasNuevaRoute: AuthenticatedCmsCategoriasNuevaRoute,
  AuthenticatedCmsRegionesEditarRoute: AuthenticatedCmsRegionesEditarRoute,
  AuthenticatedCmsRegionesNuevaRoute: AuthenticatedCmsRegionesNuevaRoute,
  AuthenticatedCmsCategoriasIndexRoute: AuthenticatedCmsCategoriasIndexRoute,
  AuthenticatedCmsRegionesIndexRoute: AuthenticatedCmsRegionesIndexRoute,
  AuthenticatedCmsReviewsIndexRoute: AuthenticatedCmsReviewsIndexRoute,
  AuthenticatedCmsReviewsIdModerarRoute: AuthenticatedCmsReviewsIdModerarRoute,
}

const AuthenticatedCmsRouteWithChildren =
  AuthenticatedCmsRoute._addFileChildren(AuthenticatedCmsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedPortalRouteRoute: typeof AuthenticatedPortalRouteRouteWithChildren
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPortalRouteRoute: AuthenticatedPortalRouteRouteWithChildren,
  AuthenticatedCmsRoute: AuthenticatedCmsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AluxRoute: AluxRoute,
  ArmaTuViajeRoute: ArmaTuViajeRoute,
  AuthRoute: AuthRoute,
  EmpresasRoute: EmpresasRoute,
  EventosRoute: EventosRoute,
  ExperienciasRoute: ExperienciasRoute,
  HotelesRoute: HotelesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantesRoute: RestaurantesRoute,
  OrienteMayaDestinoRoute: OrienteMayaDestinoRoute,
  OrienteMayaIndexRoute: OrienteMayaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
