/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AluxRouteImport } from './routes/alux'
import { Route as ArmaTuViajeRouteImport } from './routes/arma-tu-viaje'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CasasDeVacacionesRouteImport } from './routes/casas-de-vacaciones'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConvertirEnAnfitrionRouteImport } from './routes/convertir-en-anfitrion'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as HotelesRouteImport } from './routes/hoteles'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PersonalizacionRouteImport } from './routes/personalizacion'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PromocionesRouteImport } from './routes/promociones'
import { Route as QueHacerRouteImport } from './routes/que-hacer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RestaurantesRouteImport } from './routes/restaurantes'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedConciergeRouteRouteImport } from './routes/_authenticated/concierge/route'
import { Route as AuthenticatedCuentaRouteRouteImport } from './routes/_authenticated/cuenta/route'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedMiViajeRouteImport } from './routes/_authenticated/mi-viaje'
import { Route as AuthenticatedPaginasRouteImport } from './routes/_authenticated/paginas'
import { Route as AuthenticatedPortalRouteRouteImport } from './routes/_authenticated/portal/route'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as LovableBusinessMotherTemplatePreviewRouteImport } from './routes/lovable/business-mother-template-preview'
import { Route as LovableContextEnginePreviewRouteImport } from './routes/lovable/context-engine-preview'
import { Route as LovableExperienceHeroPreviewRouteImport } from './routes/lovable/experience-hero-preview'
import { Route as LovableExperienceI1cPreviewRouteImport } from './routes/lovable/experience-i1c-preview'
import { Route as LovableExperienceMapPreviewRouteImport } from './routes/lovable/experience-map-preview'
import { Route as LovableExperienceProductsPreviewRouteImport } from './routes/lovable/experience-products-preview'
import { Route as LovableExperiencePromotionsPreviewRouteImport } from './routes/lovable/experience-promotions-preview'
import { Route as LovableExperienceRelatedCollectionPreviewRouteImport } from './routes/lovable/experience-related-collection-preview'
import { Route as LovableExperienceReviewsPreviewRouteImport } from './routes/lovable/experience-reviews-preview'
import { Route as LovableExperienceSubnavCtabarPreviewRouteImport } from './routes/lovable/experience-subnav-ctabar-preview'
import { Route as LovableFounderHomePremiumPreviewRouteImport } from './routes/lovable/founder-home-premium-preview'
import { Route as LovableFounderZazilPremiumPreviewRouteImport } from './routes/lovable/founder-zazil-premium-preview'
import { Route as LovableG4DestinationMicrositePreviewRouteImport } from './routes/lovable/g4-destination-microsite-preview'
import { Route as LovableG4EventPremiumPreviewRouteImport } from './routes/lovable/g4-event-premium-preview'
import { Route as LovableG4ExperiencePremiumPreviewRouteImport } from './routes/lovable/g4-experience-premium-preview'
import { Route as LovableG4HomePremiumPreviewRouteImport } from './routes/lovable/g4-home-premium-preview'
import { Route as LovableG4HotelPremiumPreviewRouteImport } from './routes/lovable/g4-hotel-premium-preview'
import { Route as LovableG4RestaurantPremiumPreviewRouteImport } from './routes/lovable/g4-restaurant-premium-preview'
import { Route as LovableG5ListingReadinessPreviewRouteImport } from './routes/lovable/g5-listing-readiness-preview'
import { Route as LovableG6CategoryIconCatalogRouteImport } from './routes/lovable/g6-category-icon-catalog'
import { Route as LovableG8PlacePremiumVisualApprovalRouteImport } from './routes/lovable/g8-place-premium-visual-approval'
import { Route as LovableG8R1clSeoLandingParityRouteImport } from './routes/lovable/g8-r1cl-seo-landing-parity'
import { Route as LovableG8R1f1cArticlePreviewRouteImport } from './routes/lovable/g8-r1f1c-article-preview'
import { Route as LovableG8R1f1cBusinessGenericPreviewRouteImport } from './routes/lovable/g8-r1f1c-business-generic-preview'
import { Route as LovableG8R1f1cPreviewHubRouteImport } from './routes/lovable/g8-r1f1c-preview-hub'
import { Route as LovableG8R1f1cProductGenericPreviewRouteImport } from './routes/lovable/g8-r1f1c-product-generic-preview'
import { Route as LovableG8R1f1cRoutePreviewRouteImport } from './routes/lovable/g8-r1f1c-route-preview'
import { Route as LovableG8R1f1cZonePreviewRouteImport } from './routes/lovable/g8-r1f1c-zone-preview'
import { Route as LovableG8dPremiumParityRouteImport } from './routes/lovable/g8d-premium-parity'
import { Route as LovableG8ePremiumTemplateCatalogRouteImport } from './routes/lovable/g8e-premium-template-catalog'
import { Route as LovableG8p2TourPremiumPreviewRouteImport } from './routes/lovable/g8p2-tour-premium-preview'
import { Route as LovableG8p2VacationRentalPremiumPreviewRouteImport } from './routes/lovable/g8p2-vacation-rental-premium-preview'
import { Route as LovableProtectedActionsPreviewRouteImport } from './routes/lovable/protected-actions-preview'
import { Route as LovableTerritorialListingPremiumPreviewRouteImport } from './routes/lovable/territorial-listing-premium-preview'
import { Route as LovableTourismCardPreviewRouteImport } from './routes/lovable/tourism-card-preview'
import { Route as LovableWorkspaceFoundationsRouteImport } from './routes/lovable/workspace-foundations'
import { Route as LovableWorkspacePreviewRouteImport } from './routes/lovable/workspace-preview'
import { Route as MarketplaceSplatRouteImport } from './routes/marketplace.$'
import { Route as OrienteMayaIndexRouteImport } from './routes/oriente-maya/index'
import { Route as OrienteMayaDestinoRouteImport } from './routes/oriente-maya/$destino'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PreviewTokenRouteImport } from './routes/preview.$token'
import { Route as PreviewF1kDestinationsRouteImport } from './routes/preview/f1k-destinations'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as ViajeCompartidoTokenRouteImport } from './routes/viaje-compartido.$token'
import { Route as ViajeroHandleRouteImport } from './routes/viajero.$handle'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnfitrionesRouteImport } from './routes/_authenticated/admin/anfitriones'
import { Route as AuthenticatedAdminConciergeRouteImport } from './routes/_authenticated/admin/concierge'
import { Route as AuthenticatedAdminEmpresasRouteImport } from './routes/_authenticated/admin/empresas'
import { Route as AuthenticatedAdminIaRouteImport } from './routes/_authenticated/admin/ia'
import { Route as AuthenticatedAdminOperacionesRouteImport } from './routes/_authenticated/admin/operaciones'
import { Route as AuthenticatedAdminSistemaRouteImport } from './routes/_authenticated/admin/sistema'
import { Route as AuthenticatedAdminTuristasRouteImport } from './routes/_authenticated/admin/turistas'
import { Route as AuthenticatedCmsIndexRouteImport } from './routes/_authenticated/cms/index'
import { Route as AuthenticatedCmsActividadRouteImport } from './routes/_authenticated/cms/actividad'
import { Route as AuthenticatedCmsAlertasRouteImport } from './routes/_authenticated/cms/alertas'
import { Route as AuthenticatedCmsAluxRouteImport } from './routes/_authenticated/cms/alux'
import { Route as AuthenticatedCmsContenidoEvaluacionRouteImport } from './routes/_authenticated/cms/contenido-evaluacion'
import { Route as AuthenticatedCmsDemoPackRouteImport } from './routes/_authenticated/cms/demo-pack'
import { Route as AuthenticatedCmsExperienceBuilderRouteImport } from './routes/_authenticated/cms/experience-builder'
import { Route as AuthenticatedCmsMediaRouteImport } from './routes/_authenticated/cms/media'
import { Route as AuthenticatedCmsObservabilidadRouteImport } from './routes/_authenticated/cms/observabilidad'
import { Route as AuthenticatedCmsPagosRouteImport } from './routes/_authenticated/cms/pagos'
import { Route as AuthenticatedCmsRcVisualRouteImport } from './routes/_authenticated/cms/rc-visual'
import { Route as AuthenticatedCmsSimulationRouteImport } from './routes/_authenticated/cms/simulation'
import { Route as AuthenticatedCmsTravelPlansRouteImport } from './routes/_authenticated/cms/travel-plans'
import { Route as AuthenticatedCmsVentasEnLineaRouteImport } from './routes/_authenticated/cms/ventas-en-linea'
import { Route as AuthenticatedCmsVisibilidadRouteImport } from './routes/_authenticated/cms/visibilidad'
import { Route as AuthenticatedCmsVisitorIntelRouteImport } from './routes/_authenticated/cms/visitor-intel'
import { Route as AuthenticatedConciergeIndexRouteImport } from './routes/_authenticated/concierge/index'
import { Route as AuthenticatedCuentaIndexRouteImport } from './routes/_authenticated/cuenta/index'
import { Route as AuthenticatedCuentaActividadRouteImport } from './routes/_authenticated/cuenta/actividad'
import { Route as AuthenticatedCuentaAnfitrionRouteImport } from './routes/_authenticated/cuenta/anfitrion'
import { Route as AuthenticatedCuentaCarritoRouteImport } from './routes/_authenticated/cuenta/carrito'
import { Route as AuthenticatedCuentaConciergeRouteImport } from './routes/_authenticated/cuenta/concierge'
import { Route as AuthenticatedCuentaFavoritosRouteImport } from './routes/_authenticated/cuenta/favoritos'
import { Route as AuthenticatedCuentaHistorialRouteImport } from './routes/_authenticated/cuenta/historial'
import { Route as AuthenticatedCuentaMiViajeRouteImport } from './routes/_authenticated/cuenta/mi-viaje'
import { Route as AuthenticatedCuentaMisCuponesRouteImport } from './routes/_authenticated/cuenta/mis-cupones'
import { Route as AuthenticatedCuentaNotificacionesRouteImport } from './routes/_authenticated/cuenta/notificaciones'
import { Route as AuthenticatedCuentaPerfilRouteImport } from './routes/_authenticated/cuenta/perfil'
import { Route as AuthenticatedCuentaPerfilPublicoRouteImport } from './routes/_authenticated/cuenta/perfil-publico'
import { Route as AuthenticatedCuentaStageSimulatorRouteImport } from './routes/_authenticated/cuenta/stage-simulator'
import { Route as AuthenticatedPaginasSplatRouteImport } from './routes/_authenticated/paginas.$'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalActividadRouteImport } from './routes/_authenticated/portal/actividad'
import { Route as AuthenticatedPortalCanjearRouteImport } from './routes/_authenticated/portal/canjear'
import { Route as AuthenticatedPortalCanjesRouteImport } from './routes/_authenticated/portal/canjes'
import { Route as AuthenticatedPortalCatalogoRouteImport } from './routes/_authenticated/portal/catalogo'
import { Route as AuthenticatedPortalConciergeRouteImport } from './routes/_authenticated/portal/concierge'
import { Route as AuthenticatedPortalFichaRouteImport } from './routes/_authenticated/portal/ficha'
import { Route as AuthenticatedPortalGaleriaRouteImport } from './routes/_authenticated/portal/galeria'
import { Route as AuthenticatedPortalMetricasRouteImport } from './routes/_authenticated/portal/metricas'
import { Route as AuthenticatedPortalPagosRouteImport } from './routes/_authenticated/portal/pagos'
import { Route as AuthenticatedPortalPresenciaRouteImport } from './routes/_authenticated/portal/presencia'
import { Route as AuthenticatedPortalPropiedadRouteImport } from './routes/_authenticated/portal/propiedad'
import { Route as AuthenticatedPortalReportesRouteImport } from './routes/_authenticated/portal/reportes'
import { Route as AuthenticatedPortalVentasEnLineaRouteImport } from './routes/_authenticated/portal/ventas-en-linea'
import { Route as AuthenticatedPortalVisibilidadRouteImport } from './routes/_authenticated/portal/visibilidad'
import { Route as ApiDevMediaPipelineDeriveRouteImport } from './routes/api/dev/media-pipeline-derive'
import { Route as ApiDevMediaShadowEvalRouteImport } from './routes/api/dev/media-shadow-eval'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as OrienteMayaDestinoIndexRouteImport } from './routes/oriente-maya/$destino.index'
import { Route as OrienteMayaDestinoCategoriaRouteImport } from './routes/oriente-maya/$destino.$categoria'
import { Route as PreviewCompositionTokenRouteImport } from './routes/preview/composition.$token'
import { Route as ResenarNegocioSlugRouteImport } from './routes/resenar.negocio.$slug'
import { Route as AuthenticatedAdminSistemaIndexRouteImport } from './routes/_authenticated/admin/sistema.index'
import { Route as AuthenticatedAdminSistemaUsuariosRouteImport } from './routes/_authenticated/admin/sistema.usuarios'
import { Route as AuthenticatedCmsAluxCalidadRouteImport } from './routes/_authenticated/cms/alux.calidad'
import { Route as AuthenticatedCmsAluxConocimientoRouteImport } from './routes/_authenticated/cms/alux.conocimiento'
import { Route as AuthenticatedCmsAluxFeedbackRouteImport } from './routes/_authenticated/cms/alux.feedback'
import { Route as AuthenticatedCmsCategoriasIndexRouteImport } from './routes/_authenticated/cms/categorias.index'
import { Route as AuthenticatedCmsCategoriasNuevaRouteImport } from './routes/_authenticated/cms/categorias.nueva'
import { Route as AuthenticatedCmsDestinosIndexRouteImport } from './routes/_authenticated/cms/destinos.index'
import { Route as AuthenticatedCmsDestinosNuevaRouteImport } from './routes/_authenticated/cms/destinos.nueva'
import { Route as AuthenticatedCmsEmpresasIndexRouteImport } from './routes/_authenticated/cms/empresas.index'
import { Route as AuthenticatedCmsEmpresasNuevaRouteImport } from './routes/_authenticated/cms/empresas.nueva'
import { Route as AuthenticatedCmsExperienceBuilderInventoryRouteImport } from './routes/_authenticated/cms/experience-builder.inventory'
import { Route as AuthenticatedCmsExperienceBuilderPagesRouteImport } from './routes/_authenticated/cms/experience-builder.pages'
import { Route as AuthenticatedCmsLugaresIndexRouteImport } from './routes/_authenticated/cms/lugares.index'
import { Route as AuthenticatedCmsLugaresNuevoRouteImport } from './routes/_authenticated/cms/lugares.nuevo'
import { Route as AuthenticatedCmsProductosIndexRouteImport } from './routes/_authenticated/cms/productos.index'
import { Route as AuthenticatedCmsProductosNuevaRouteImport } from './routes/_authenticated/cms/productos.nueva'
import { Route as AuthenticatedCmsRegionesIndexRouteImport } from './routes/_authenticated/cms/regiones.index'
import { Route as AuthenticatedCmsRegionesNuevaRouteImport } from './routes/_authenticated/cms/regiones.nueva'
import { Route as AuthenticatedCmsRelacionadosIndexRouteImport } from './routes/_authenticated/cms/relacionados.index'
import { Route as AuthenticatedCmsReviewsIndexRouteImport } from './routes/_authenticated/cms/reviews.index'
import { Route as AuthenticatedCmsVisibilidadSolicitudesRouteImport } from './routes/_authenticated/cms/visibilidad.solicitudes'
import { Route as AuthenticatedCmsVisibilidadSpotlightRouteImport } from './routes/_authenticated/cms/visibilidad.spotlight'
import { Route as AuthenticatedCmsVisitorIntelDecisionsRouteImport } from './routes/_authenticated/cms/visitor-intel_.decisions'
import { Route as AuthenticatedCmsZonasIndexRouteImport } from './routes/_authenticated/cms/zonas.index'
import { Route as AuthenticatedCmsZonasNuevaRouteImport } from './routes/_authenticated/cms/zonas.nueva'
import { Route as AuthenticatedConciergeExpedientesCaseIdRouteImport } from './routes/_authenticated/concierge/expedientes.$caseId'
import { Route as AuthenticatedCuentaCheckoutOrderIdRouteImport } from './routes/_authenticated/cuenta/checkout.$orderId'
import { Route as AuthenticatedCuentaConciergeCaseIdRouteImport } from './routes/_authenticated/cuenta/concierge.$caseId'
import { Route as AuthenticatedCuentaDocumentosOrderIdRouteImport } from './routes/_authenticated/cuenta/documentos.$orderId'
import { Route as AuthenticatedCuentaPagosErrorRouteImport } from './routes/_authenticated/cuenta/pagos.error'
import { Route as AuthenticatedCuentaPagosExitoRouteImport } from './routes/_authenticated/cuenta/pagos.exito'
import { Route as AuthenticatedPortalEmpresasIndexRouteImport } from './routes/_authenticated/portal/empresas.index'
import { Route as AuthenticatedPortalEmpresasBusinessIdRouteImport } from './routes/_authenticated/portal/empresas.$businessId'
import { Route as AuthenticatedPortalInvitacionesIndexRouteImport } from './routes/_authenticated/portal/invitaciones.index'
import { Route as AuthenticatedPortalInvitacionesTokenRouteImport } from './routes/_authenticated/portal/invitaciones.$token'
import { Route as AuthenticatedPortalResenasIndexRouteImport } from './routes/_authenticated/portal/resenas.index'
import { Route as AuthenticatedPortalVentasEnLineaOrdenesRouteImport } from './routes/_authenticated/portal/ventas-en-linea.ordenes'
import { Route as ApiPublicAluxChatRouteImport } from './routes/api/public/alux/chat'
import { Route as ApiPublicAluxSignalRouteImport } from './routes/api/public/alux/signal'
import { Route as ApiPublicHealthMapsRouteImport } from './routes/api/public/health/maps'
import { Route as ApiPublicHooksCouponReviewRemindersRouteImport } from './routes/api/public/hooks/coupon-review-reminders'
import { Route as ApiPublicHooksEbProcessScheduledPublishRouteImport } from './routes/api/public/hooks/eb-process-scheduled-publish'
import { Route as ApiPublicHooksMediaSignatureRenewRouteImport } from './routes/api/public/hooks/media-signature-renew'
import { Route as ApiPublicHooksTripJourneyEmailsRouteImport } from './routes/api/public/hooks/trip-journey-emails'
import { Route as ApiPublicHooksVisibilityNotificationsRouteImport } from './routes/api/public/hooks/visibility-notifications'
import { Route as ApiPublicMapsStaticRouteImport } from './routes/api/public/maps/static'
import { Route as ApiPublicStudioMediaSplatRouteImport } from './routes/api/public/studio-media.$'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as OrienteMayaDestinoCategoriaIndexRouteImport } from './routes/oriente-maya/$destino.$categoria.index'
import { Route as OrienteMayaDestinoCategoriaEmpresaRouteImport } from './routes/oriente-maya/$destino.$categoria.$empresa'
import { Route as OrienteMayaDestinoLugaresSlugRouteImport } from './routes/oriente-maya/$destino.lugares.$slug'
import { Route as AuthenticatedCmsCategoriasIdEditarRouteImport } from './routes/_authenticated/cms/categorias.$id.editar'
import { Route as AuthenticatedCmsDestinosDestinationIdEditarRouteImport } from './routes/_authenticated/cms/destinos.$destinationId.editar'
import { Route as AuthenticatedCmsEmpresasBusinessIdEditarRouteImport } from './routes/_authenticated/cms/empresas.$businessId.editar'
import { Route as AuthenticatedCmsEmpresasBusinessIdPreviewRouteImport } from './routes/_authenticated/cms/empresas.$businessId.preview'
import { Route as AuthenticatedCmsLugaresPlaceIdEditarRouteImport } from './routes/_authenticated/cms/lugares.$placeId.editar'
import { Route as AuthenticatedCmsProductosProductIdEditarRouteImport } from './routes/_authenticated/cms/productos.$productId.editar'
import { Route as AuthenticatedCmsRegionesIdEditarRouteImport } from './routes/_authenticated/cms/regiones.$id.editar'
import { Route as AuthenticatedCmsReviewsIdModerarRouteImport } from './routes/_authenticated/cms/reviews.$id.moderar'
import { Route as AuthenticatedCmsZonasIdEditarRouteImport } from './routes/_authenticated/cms/zonas.$id.editar'
import { Route as AuthenticatedCuentaConciergeCaseIdEvaluarRouteImport } from './routes/_authenticated/cuenta/concierge.$caseId.evaluar'
import { Route as AuthenticatedCuentaEmpresaBusinessIdPublicacionRouteImport } from './routes/_authenticated/cuenta/empresa.$businessId.publicacion'
import { Route as AuthenticatedPortalProductosProductIdPreviewRouteImport } from './routes/_authenticated/portal/productos.$productId.preview'
import { Route as ApiPublicPaymentsProviderWebhookRouteImport } from './routes/api/public/payments/$provider/webhook'
import { Route as OrienteMayaDestinoCategoriaEmpresaIndexRouteImport } from './routes/oriente-maya/$destino.$categoria.$empresa.index'
import { Route as OrienteMayaDestinoCategoriaEmpresaProductoRouteImport } from './routes/oriente-maya/$destino.$categoria.$empresa.$producto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AluxRoute = AluxRouteImport.update({
  id: '/alux',
  path: '/alux',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmaTuViajeRoute = ArmaTuViajeRouteImport.update({
  id: '/arma-tu-viaje',
  path: '/arma-tu-viaje',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CasasDeVacacionesRoute = CasasDeVacacionesRouteImport.update({
  id: '/casas-de-vacaciones',
  path: '/casas-de-vacaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertirEnAnfitrionRoute = ConvertirEnAnfitrionRouteImport.update({
  id: '/convertir-en-anfitrion',
  path: '/convertir-en-anfitrion',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelesRoute = HotelesRouteImport.update({
  id: '/hoteles',
  path: '/hoteles',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizacionRoute = PersonalizacionRouteImport.update({
  id: '/personalizacion',
  path: '/personalizacion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocionesRoute = PromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => rootRouteImport,
} as any)
const QueHacerRoute = QueHacerRouteImport.update({
  id: '/que-hacer',
  path: '/que-hacer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantesRoute = RestaurantesRouteImport.update({
  id: '/restaurantes',
  path: '/restaurantes',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConciergeRouteRoute =
  AuthenticatedConciergeRouteRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCuentaRouteRoute =
  AuthenticatedCuentaRouteRouteImport.update({
    id: '/cuenta',
    path: '/cuenta',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMiViajeRoute = AuthenticatedMiViajeRouteImport.update({
  id: '/mi-viaje',
  path: '/mi-viaje',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaginasRoute = AuthenticatedPaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalRouteRoute =
  AuthenticatedPortalRouteRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventosRoute,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventosRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableBusinessMotherTemplatePreviewRoute =
  LovableBusinessMotherTemplatePreviewRouteImport.update({
    id: '/lovable/business-mother-template-preview',
    path: '/lovable/business-mother-template-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableContextEnginePreviewRoute =
  LovableContextEnginePreviewRouteImport.update({
    id: '/lovable/context-engine-preview',
    path: '/lovable/context-engine-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceHeroPreviewRoute =
  LovableExperienceHeroPreviewRouteImport.update({
    id: '/lovable/experience-hero-preview',
    path: '/lovable/experience-hero-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceI1cPreviewRoute =
  LovableExperienceI1cPreviewRouteImport.update({
    id: '/lovable/experience-i1c-preview',
    path: '/lovable/experience-i1c-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceMapPreviewRoute =
  LovableExperienceMapPreviewRouteImport.update({
    id: '/lovable/experience-map-preview',
    path: '/lovable/experience-map-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceProductsPreviewRoute =
  LovableExperienceProductsPreviewRouteImport.update({
    id: '/lovable/experience-products-preview',
    path: '/lovable/experience-products-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperiencePromotionsPreviewRoute =
  LovableExperiencePromotionsPreviewRouteImport.update({
    id: '/lovable/experience-promotions-preview',
    path: '/lovable/experience-promotions-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceRelatedCollectionPreviewRoute =
  LovableExperienceRelatedCollectionPreviewRouteImport.update({
    id: '/lovable/experience-related-collection-preview',
    path: '/lovable/experience-related-collection-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceReviewsPreviewRoute =
  LovableExperienceReviewsPreviewRouteImport.update({
    id: '/lovable/experience-reviews-preview',
    path: '/lovable/experience-reviews-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableExperienceSubnavCtabarPreviewRoute =
  LovableExperienceSubnavCtabarPreviewRouteImport.update({
    id: '/lovable/experience-subnav-ctabar-preview',
    path: '/lovable/experience-subnav-ctabar-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableFounderHomePremiumPreviewRoute =
  LovableFounderHomePremiumPreviewRouteImport.update({
    id: '/lovable/founder-home-premium-preview',
    path: '/lovable/founder-home-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableFounderZazilPremiumPreviewRoute =
  LovableFounderZazilPremiumPreviewRouteImport.update({
    id: '/lovable/founder-zazil-premium-preview',
    path: '/lovable/founder-zazil-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG4DestinationMicrositePreviewRoute =
  LovableG4DestinationMicrositePreviewRouteImport.update({
    id: '/lovable/g4-destination-microsite-preview',
    path: '/lovable/g4-destination-microsite-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG4EventPremiumPreviewRoute =
  LovableG4EventPremiumPreviewRouteImport.update({
    id: '/lovable/g4-event-premium-preview',
    path: '/lovable/g4-event-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG4ExperiencePremiumPreviewRoute =
  LovableG4ExperiencePremiumPreviewRouteImport.update({
    id: '/lovable/g4-experience-premium-preview',
    path: '/lovable/g4-experience-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG4HomePremiumPreviewRoute =
  LovableG4HomePremiumPreviewRouteImport.update({
    id: '/lovable/g4-home-premium-preview',
    path: '/lovable/g4-home-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG4HotelPremiumPreviewRoute =
  LovableG4HotelPremiumPreviewRouteImport.update({
    id: '/lovable/g4-hotel-premium-preview',
    path: '/lovable/g4-hotel-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG4RestaurantPremiumPreviewRoute =
  LovableG4RestaurantPremiumPreviewRouteImport.update({
    id: '/lovable/g4-restaurant-premium-preview',
    path: '/lovable/g4-restaurant-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG5ListingReadinessPreviewRoute =
  LovableG5ListingReadinessPreviewRouteImport.update({
    id: '/lovable/g5-listing-readiness-preview',
    path: '/lovable/g5-listing-readiness-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG6CategoryIconCatalogRoute =
  LovableG6CategoryIconCatalogRouteImport.update({
    id: '/lovable/g6-category-icon-catalog',
    path: '/lovable/g6-category-icon-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8PlacePremiumVisualApprovalRoute =
  LovableG8PlacePremiumVisualApprovalRouteImport.update({
    id: '/lovable/g8-place-premium-visual-approval',
    path: '/lovable/g8-place-premium-visual-approval',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1clSeoLandingParityRoute =
  LovableG8R1clSeoLandingParityRouteImport.update({
    id: '/lovable/g8-r1cl-seo-landing-parity',
    path: '/lovable/g8-r1cl-seo-landing-parity',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1f1cArticlePreviewRoute =
  LovableG8R1f1cArticlePreviewRouteImport.update({
    id: '/lovable/g8-r1f1c-article-preview',
    path: '/lovable/g8-r1f1c-article-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1f1cBusinessGenericPreviewRoute =
  LovableG8R1f1cBusinessGenericPreviewRouteImport.update({
    id: '/lovable/g8-r1f1c-business-generic-preview',
    path: '/lovable/g8-r1f1c-business-generic-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1f1cPreviewHubRoute =
  LovableG8R1f1cPreviewHubRouteImport.update({
    id: '/lovable/g8-r1f1c-preview-hub',
    path: '/lovable/g8-r1f1c-preview-hub',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1f1cProductGenericPreviewRoute =
  LovableG8R1f1cProductGenericPreviewRouteImport.update({
    id: '/lovable/g8-r1f1c-product-generic-preview',
    path: '/lovable/g8-r1f1c-product-generic-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1f1cRoutePreviewRoute =
  LovableG8R1f1cRoutePreviewRouteImport.update({
    id: '/lovable/g8-r1f1c-route-preview',
    path: '/lovable/g8-r1f1c-route-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8R1f1cZonePreviewRoute =
  LovableG8R1f1cZonePreviewRouteImport.update({
    id: '/lovable/g8-r1f1c-zone-preview',
    path: '/lovable/g8-r1f1c-zone-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8dPremiumParityRoute = LovableG8dPremiumParityRouteImport.update({
  id: '/lovable/g8d-premium-parity',
  path: '/lovable/g8d-premium-parity',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableG8ePremiumTemplateCatalogRoute =
  LovableG8ePremiumTemplateCatalogRouteImport.update({
    id: '/lovable/g8e-premium-template-catalog',
    path: '/lovable/g8e-premium-template-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8p2TourPremiumPreviewRoute =
  LovableG8p2TourPremiumPreviewRouteImport.update({
    id: '/lovable/g8p2-tour-premium-preview',
    path: '/lovable/g8p2-tour-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableG8p2VacationRentalPremiumPreviewRoute =
  LovableG8p2VacationRentalPremiumPreviewRouteImport.update({
    id: '/lovable/g8p2-vacation-rental-premium-preview',
    path: '/lovable/g8p2-vacation-rental-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableProtectedActionsPreviewRoute =
  LovableProtectedActionsPreviewRouteImport.update({
    id: '/lovable/protected-actions-preview',
    path: '/lovable/protected-actions-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableTerritorialListingPremiumPreviewRoute =
  LovableTerritorialListingPremiumPreviewRouteImport.update({
    id: '/lovable/territorial-listing-premium-preview',
    path: '/lovable/territorial-listing-premium-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableTourismCardPreviewRoute =
  LovableTourismCardPreviewRouteImport.update({
    id: '/lovable/tourism-card-preview',
    path: '/lovable/tourism-card-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableWorkspaceFoundationsRoute =
  LovableWorkspaceFoundationsRouteImport.update({
    id: '/lovable/workspace-foundations',
    path: '/lovable/workspace-foundations',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableWorkspacePreviewRoute = LovableWorkspacePreviewRouteImport.update({
  id: '/lovable/workspace-preview',
  path: '/lovable/workspace-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSplatRoute = MarketplaceSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MarketplaceRoute,
} as any)
const OrienteMayaIndexRoute = OrienteMayaIndexRouteImport.update({
  id: '/oriente-maya/',
  path: '/oriente-maya/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrienteMayaDestinoRoute = OrienteMayaDestinoRouteImport.update({
  id: '/oriente-maya/$destino',
  path: '/oriente-maya/$destino',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewTokenRoute = PreviewTokenRouteImport.update({
  id: '/preview/$token',
  path: '/preview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewF1kDestinationsRoute = PreviewF1kDestinationsRouteImport.update({
  id: '/preview/f1k-destinations',
  path: '/preview/f1k-destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajeCompartidoTokenRoute = ViajeCompartidoTokenRouteImport.update({
  id: '/viaje-compartido/$token',
  path: '/viaje-compartido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajeroHandleRoute = ViajeroHandleRouteImport.update({
  id: '/viajero/$handle',
  path: '/viajero/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnfitrionesRoute =
  AuthenticatedAdminAnfitrionesRouteImport.update({
    id: '/anfitriones',
    path: '/anfitriones',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConciergeRoute =
  AuthenticatedAdminConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresasRoute =
  AuthenticatedAdminEmpresasRouteImport.update({
    id: '/empresas',
    path: '/empresas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminIaRoute = AuthenticatedAdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminOperacionesRoute =
  AuthenticatedAdminOperacionesRouteImport.update({
    id: '/operaciones',
    path: '/operaciones',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSistemaRoute =
  AuthenticatedAdminSistemaRouteImport.update({
    id: '/sistema',
    path: '/sistema',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTuristasRoute =
  AuthenticatedAdminTuristasRouteImport.update({
    id: '/turistas',
    path: '/turistas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCmsIndexRoute = AuthenticatedCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsActividadRoute =
  AuthenticatedCmsActividadRouteImport.update({
    id: '/actividad',
    path: '/actividad',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsAlertasRoute = AuthenticatedCmsAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsAluxRoute = AuthenticatedCmsAluxRouteImport.update({
  id: '/alux',
  path: '/alux',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsContenidoEvaluacionRoute =
  AuthenticatedCmsContenidoEvaluacionRouteImport.update({
    id: '/contenido-evaluacion',
    path: '/contenido-evaluacion',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsDemoPackRoute =
  AuthenticatedCmsDemoPackRouteImport.update({
    id: '/demo-pack',
    path: '/demo-pack',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsExperienceBuilderRoute =
  AuthenticatedCmsExperienceBuilderRouteImport.update({
    id: '/experience-builder',
    path: '/experience-builder',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsMediaRoute = AuthenticatedCmsMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsObservabilidadRoute =
  AuthenticatedCmsObservabilidadRouteImport.update({
    id: '/observabilidad',
    path: '/observabilidad',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsPagosRoute = AuthenticatedCmsPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthenticatedCmsRoute,
} as any)
const AuthenticatedCmsRcVisualRoute =
  AuthenticatedCmsRcVisualRouteImport.update({
    id: '/rc-visual',
    path: '/rc-visual',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsSimulationRoute =
  AuthenticatedCmsSimulationRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsTravelPlansRoute =
  AuthenticatedCmsTravelPlansRouteImport.update({
    id: '/travel-plans',
    path: '/travel-plans',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsVentasEnLineaRoute =
  AuthenticatedCmsVentasEnLineaRouteImport.update({
    id: '/ventas-en-linea',
    path: '/ventas-en-linea',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsVisibilidadRoute =
  AuthenticatedCmsVisibilidadRouteImport.update({
    id: '/visibilidad',
    path: '/visibilidad',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsVisitorIntelRoute =
  AuthenticatedCmsVisitorIntelRouteImport.update({
    id: '/visitor-intel',
    path: '/visitor-intel',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedConciergeIndexRoute =
  AuthenticatedConciergeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConciergeRouteRoute,
  } as any)
const AuthenticatedCuentaIndexRoute =
  AuthenticatedCuentaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaActividadRoute =
  AuthenticatedCuentaActividadRouteImport.update({
    id: '/actividad',
    path: '/actividad',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaAnfitrionRoute =
  AuthenticatedCuentaAnfitrionRouteImport.update({
    id: '/anfitrion',
    path: '/anfitrion',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaCarritoRoute =
  AuthenticatedCuentaCarritoRouteImport.update({
    id: '/carrito',
    path: '/carrito',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaConciergeRoute =
  AuthenticatedCuentaConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaFavoritosRoute =
  AuthenticatedCuentaFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaHistorialRoute =
  AuthenticatedCuentaHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaMiViajeRoute =
  AuthenticatedCuentaMiViajeRouteImport.update({
    id: '/mi-viaje',
    path: '/mi-viaje',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaMisCuponesRoute =
  AuthenticatedCuentaMisCuponesRouteImport.update({
    id: '/mis-cupones',
    path: '/mis-cupones',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaNotificacionesRoute =
  AuthenticatedCuentaNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaPerfilRoute =
  AuthenticatedCuentaPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaPerfilPublicoRoute =
  AuthenticatedCuentaPerfilPublicoRouteImport.update({
    id: '/perfil-publico',
    path: '/perfil-publico',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedCuentaStageSimulatorRoute =
  AuthenticatedCuentaStageSimulatorRouteImport.update({
    id: '/stage-simulator',
    path: '/stage-simulator',
    getParentRoute: () => AuthenticatedCuentaRouteRoute,
  } as any)
const AuthenticatedPaginasSplatRoute =
  AuthenticatedPaginasSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => AuthenticatedPaginasRoute,
  } as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalActividadRoute =
  AuthenticatedPortalActividadRouteImport.update({
    id: '/actividad',
    path: '/actividad',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCanjearRoute =
  AuthenticatedPortalCanjearRouteImport.update({
    id: '/canjear',
    path: '/canjear',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCanjesRoute =
  AuthenticatedPortalCanjesRouteImport.update({
    id: '/canjes',
    path: '/canjes',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalCatalogoRoute =
  AuthenticatedPortalCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalConciergeRoute =
  AuthenticatedPortalConciergeRouteImport.update({
    id: '/concierge',
    path: '/concierge',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalFichaRoute =
  AuthenticatedPortalFichaRouteImport.update({
    id: '/ficha',
    path: '/ficha',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalGaleriaRoute =
  AuthenticatedPortalGaleriaRouteImport.update({
    id: '/galeria',
    path: '/galeria',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalMetricasRoute =
  AuthenticatedPortalMetricasRouteImport.update({
    id: '/metricas',
    path: '/metricas',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPagosRoute =
  AuthenticatedPortalPagosRouteImport.update({
    id: '/pagos',
    path: '/pagos',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPresenciaRoute =
  AuthenticatedPortalPresenciaRouteImport.update({
    id: '/presencia',
    path: '/presencia',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalPropiedadRoute =
  AuthenticatedPortalPropiedadRouteImport.update({
    id: '/propiedad',
    path: '/propiedad',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalReportesRoute =
  AuthenticatedPortalReportesRouteImport.update({
    id: '/reportes',
    path: '/reportes',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalVentasEnLineaRoute =
  AuthenticatedPortalVentasEnLineaRouteImport.update({
    id: '/ventas-en-linea',
    path: '/ventas-en-linea',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const AuthenticatedPortalVisibilidadRoute =
  AuthenticatedPortalVisibilidadRouteImport.update({
    id: '/visibilidad',
    path: '/visibilidad',
    getParentRoute: () => AuthenticatedPortalRouteRoute,
  } as any)
const ApiDevMediaPipelineDeriveRoute =
  ApiDevMediaPipelineDeriveRouteImport.update({
    id: '/api/dev/media-pipeline-derive',
    path: '/api/dev/media-pipeline-derive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDevMediaShadowEvalRoute = ApiDevMediaShadowEvalRouteImport.update({
  id: '/api/dev/media-shadow-eval',
  path: '/api/dev/media-shadow-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const OrienteMayaDestinoIndexRoute = OrienteMayaDestinoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrienteMayaDestinoRoute,
} as any)
const OrienteMayaDestinoCategoriaRoute =
  OrienteMayaDestinoCategoriaRouteImport.update({
    id: '/$categoria',
    path: '/$categoria',
    getParentRoute: () => OrienteMayaDestinoRoute,
  } as any)
const PreviewCompositionTokenRoute = PreviewCompositionTokenRouteImport.update({
  id: '/preview/composition/$token',
  path: '/preview/composition/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResenarNegocioSlugRoute = ResenarNegocioSlugRouteImport.update({
  id: '/resenar/negocio/$slug',
  path: '/resenar/negocio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSistemaIndexRoute =
  AuthenticatedAdminSistemaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSistemaRoute,
  } as any)
const AuthenticatedAdminSistemaUsuariosRoute =
  AuthenticatedAdminSistemaUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminSistemaRoute,
  } as any)
const AuthenticatedCmsAluxCalidadRoute =
  AuthenticatedCmsAluxCalidadRouteImport.update({
    id: '/calidad',
    path: '/calidad',
    getParentRoute: () => AuthenticatedCmsAluxRoute,
  } as any)
const AuthenticatedCmsAluxConocimientoRoute =
  AuthenticatedCmsAluxConocimientoRouteImport.update({
    id: '/conocimiento',
    path: '/conocimiento',
    getParentRoute: () => AuthenticatedCmsAluxRoute,
  } as any)
const AuthenticatedCmsAluxFeedbackRoute =
  AuthenticatedCmsAluxFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedCmsAluxRoute,
  } as any)
const AuthenticatedCmsCategoriasIndexRoute =
  AuthenticatedCmsCategoriasIndexRouteImport.update({
    id: '/categorias/',
    path: '/categorias/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsCategoriasNuevaRoute =
  AuthenticatedCmsCategoriasNuevaRouteImport.update({
    id: '/categorias/nueva',
    path: '/categorias/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsDestinosIndexRoute =
  AuthenticatedCmsDestinosIndexRouteImport.update({
    id: '/destinos/',
    path: '/destinos/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsDestinosNuevaRoute =
  AuthenticatedCmsDestinosNuevaRouteImport.update({
    id: '/destinos/nueva',
    path: '/destinos/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsEmpresasIndexRoute =
  AuthenticatedCmsEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsEmpresasNuevaRoute =
  AuthenticatedCmsEmpresasNuevaRouteImport.update({
    id: '/empresas/nueva',
    path: '/empresas/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsExperienceBuilderInventoryRoute =
  AuthenticatedCmsExperienceBuilderInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedCmsExperienceBuilderRoute,
  } as any)
const AuthenticatedCmsExperienceBuilderPagesRoute =
  AuthenticatedCmsExperienceBuilderPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedCmsExperienceBuilderRoute,
  } as any)
const AuthenticatedCmsLugaresIndexRoute =
  AuthenticatedCmsLugaresIndexRouteImport.update({
    id: '/lugares/',
    path: '/lugares/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsLugaresNuevoRoute =
  AuthenticatedCmsLugaresNuevoRouteImport.update({
    id: '/lugares/nuevo',
    path: '/lugares/nuevo',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsProductosIndexRoute =
  AuthenticatedCmsProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsProductosNuevaRoute =
  AuthenticatedCmsProductosNuevaRouteImport.update({
    id: '/productos/nueva',
    path: '/productos/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsRegionesIndexRoute =
  AuthenticatedCmsRegionesIndexRouteImport.update({
    id: '/regiones/',
    path: '/regiones/',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsRegionesNuevaRoute =
  AuthenticatedCmsRegionesNuevaRouteImport.update({
    id: '/regiones/nueva',
    path: '/regiones/nueva',
    getParentRoute: () => AuthenticatedCmsRoute,
  } as any)
const AuthenticatedCmsRelacionadosIndexRoute =
  AuthenticatedCmsRelacionadosIndexRouteImport.update({
