INSERT INTO public.events (slug, title, summary, body, locale, status, destination_id, starts_at, ends_at, venue_name, is_free, published_at, is_demo_seed, demo_seed_batch, filter_attributes)
SELECT v.slug, v.title, v.summary, v.body, 'es'::locale_code, 'published'::content_status, v.destination_id, v.starts_at, v.ends_at, v.venue_name, v.is_free, now(), true, 'EVENTS-FILTER-VALIDATION-2026-09', v.filter_attributes
FROM (VALUES
 ('val-serenata-parque-principal','Serenata en el Parque Principal','Música yucateca en vivo frente al templo de San Servacio.','Cada semana la plaza principal se llena de trova y baile regional al caer la tarde.','11111111-aaaa-4aaa-8aaa-000000000001'::uuid, now() + interval '6 hours', now() + interval '9 hours','Parque Principal Francisco Cantón', true, '{"event_type":"musica","audience":["familias","parejas"],"admission_type":"entrada-libre","time_of_day":["noche"],"venue_type":"plaza-publica","accessibility":["acceso-silla-ruedas","apto-movilidad-reducida"],"reservation_required":"sin-reservacion"}'::jsonb),
 ('val-mercado-gastronomico-calzada','Mercado Gastronómico de la Calzada','Cocineras tradicionales y productores locales del oriente de Yucatán.','Degustación de recados, relleno negro, longaniza y dulces regionales.','11111111-aaaa-4aaa-8aaa-000000000001'::uuid, now() + interval '2 days', now() + interval '2 days 8 hours','Calzada de los Frailes', false, '{"event_type":"gastronomia","audience":["familias","amigos"],"admission_type":"de-pago","time_of_day":["tarde","noche"],"venue_type":"aire-libre","accessibility":["sanitarios-accesibles"],"reservation_required":"sin-reservacion"}'::jsonb),
 ('val-taller-urdido-hamaca','Taller de Urdido de Hamaca','Aprende el urdido tradicional con artesanas de la región.','Sesión práctica de tres horas con materiales incluidos y cupo limitado.','11111111-aaaa-4aaa-8aaa-000000000001'::uuid, now() + interval '5 days', now() + interval '5 days 3 hours','Casa de la Cultura', false, '{"event_type":"tradicion","audience":["adultos","parejas"],"admission_type":"de-pago","time_of_day":["manana"],"venue_type":"recinto-cerrado","accessibility":["acceso-silla-ruedas"],"reservation_required":"con-reservacion"}'::jsonb),
 ('val-carrera-nocturna-centro','Carrera Nocturna del Centro Histórico','Ruta de 5 y 10 km por calles coloniales iluminadas.','Salida y meta en el Parque Principal, con hidratación y guardarropa.','11111111-aaaa-4aaa-8aaa-000000000001'::uuid, now() + interval '20 days', now() + interval '20 days 4 hours','Centro Histórico', false, '{"event_type":"deportivo","audience":["amigos","adultos"],"admission_type":"de-pago","time_of_day":["noche"],"venue_type":"aire-libre","accessibility":[],"reservation_required":"con-reservacion"}'::jsonb),
 ('izamal-procesion-luz-convento','Procesión de Luz en el Convento','Recorrido con velas en el atrio del convento de San Antonio de Padua.','Actividad comunitaria abierta al público, con música sacra.','11111111-aaaa-4aaa-8aaa-000000000005'::uuid, now() + interval '3 days', now() + interval '3 days 3 hours','Convento de San Antonio de Padua', true, '{"event_type":"cultural","audience":["familias","adultos"],"admission_type":"entrada-libre","time_of_day":["noche"],"venue_type":"templo-convento","accessibility":["acceso-silla-ruedas","estacionamiento-accesible"],"reservation_required":"sin-reservacion"}'::jsonb),
 ('izamal-feria-artesanal-amarilla','Feria Artesanal Ciudad Amarilla','Talleres familiares de talla en madera, joyería y bordado.','Los artesanos muestran su proceso y venden directamente al visitante.','11111111-aaaa-4aaa-8aaa-000000000005'::uuid, now() + interval '38 days', now() + interval '40 days','Plaza Zamná', true, '{"event_type":"feria","audience":["familias","ninos"],"admission_type":"entrada-libre","time_of_day":["manana","tarde"],"venue_type":"plaza-publica","accessibility":["sanitarios-accesibles","apto-movilidad-reducida"],"reservation_required":"sin-reservacion"}'::jsonb),
 ('espita-noche-boleros-plaza','Noche de Boleros en la Plaza','Tríos y voces del oriente maya bajo los laureles de la plaza.','Programa gratuito con presentación de agrupaciones locales.','cf58a91a-96ec-4ba5-948b-e91fefc5ee47'::uuid, now() + interval '3 days 4 hours', now() + interval '3 days 7 hours','Plaza Principal de Espita', true, '{"event_type":"musica","audience":["parejas","adultos"],"admission_type":"entrada-libre","time_of_day":["noche"],"venue_type":"plaza-publica","accessibility":["apto-movilidad-reducida"],"reservation_required":"sin-reservacion"}'::jsonb),
 ('espita-encuentro-hipil-comunitario','Encuentro Comunitario del Hipil','Muestra de bordado y desfile de hipiles tradicionales.','Encuentro con talleres abiertos y venta directa de bordadoras.','cf58a91a-96ec-4ba5-948b-e91fefc5ee47'::uuid, now() + interval '45 days', now() + interval '45 days 6 hours','Casa Ejidal', false, '{"event_type":"comunitario","audience":["familias","adultos"],"admission_type":"donativo","time_of_day":["todo-el-dia"],"venue_type":"comunidad","accessibility":[],"reservation_required":"sin-reservacion"}'::jsonb)
) AS v(slug, title, summary, body, destination_id, starts_at, ends_at, venue_name, is_free, filter_attributes)
WHERE NOT EXISTS (SELECT 1 FROM public.events e WHERE e.slug = v.slug);